# 指定 SOURCES 变量 (也可以采用默认值: 自动非递归地读取本目录的 tex 文件)
# SOURCES = starred-sections-and-table-of-contents-1.tex \
#           starred-sections-and-table-of-contents-2.tex

# 包含规则定义文件
include ../../Makefile

