SOURCES = chapter-installation.tex \
  chapter-fonts.tex \
  chapter-latex-workshop.tex \
  chapter-formulas.tex \
  chapter-theorems.tex \
  chapter-algorithms.tex \
  chapter-codelistings.tex \
  chapter-troubleshooting.tex \
  latex-essentials.tex

include ../Makefile

#chapter-algorithms.pdf: chapter-algorithms.tex references.bib

#chapter-formulas.pdf: chapter-formulas.tex references.bib

#chapter-tikz-preliminaries.pdf: chapter-tikz-preliminaries.tex references.bib
